# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://www.animaquina.com" 
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ""

# Title of the Site
title: Animaquina
# Description of the Site
description:  Robot Control
# URL of Image of the Site
site-image: /assets/images/icon.png
# Keywords of the Site
site-keywords: Robot, control, digital fabrication
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/test.gif

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: luis.pacheco@neobrutal.com
#facebook_username: thedevslot
#twitter_username: thedevslot
instagram_username: animaquina_
#linkedin_username: thedevslot
#github_username:  thedevslot
youtube: codedvoxels
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: Animaquina
# URL for the Image of the Author
author-image: /assets/images/icon.png
# 60 Words About the Author
author-about: Animaquina is a robot Integrated Development Environment (IDE) designed for controlling and simulating Robots within Blender. It leverages Blender's powerful 3D capabilities to provide a versatile platform for robot programming and visualization.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://www.luigipacheco.com/

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
